# Generated by Django 6.1 on 2026-09-14 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('professional', 'Professional'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
