# Generated by Django 6.1 on 2026-09-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
