# Generated by Django 6.1 on 2026-09-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_awards_awarded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='awarded_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
